name: Tools preview on PR level

on:
  pull_request_target:
    types:
      - synchronize
      - edited

jobs:
  suggestChanges:
    if: github.repository == 'princerajpoot20/bot-testing'
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Regenerate
        run: npm run generate:tools
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "tools::changed"
          echo ::set-output name=tools_changed::$(git diff --exit-code; echo $?)
      - name: Commit and push if there are changes
        if: steps.git-check.outputs.tools_changed == '1'
        run: |
          git config --global user.name 'princerajpoot-bot'
          git config --global user.email 'princerajpoot-bot@github.com'
          git add -A
          git commit -m "Regenerate tools section"
          git push
      - name: Create PR Review with suggestions
        if: steps.git-check.outputs.tools_changed == '1'
        run: |
          gh pr review ${{ github.event.pull_request.number }} --comment -b "Suggested changes after regenerating the tools section. Please review and merge if appropriate."
        env:
          GH_CLI_TOKEN: ${{ secrets.GH_TOKEN }}
