name: Review with Suggestions for Tool Changes

on:
  pull_request_target:
    types:
      - synchronize
      - edited

jobs:
  reviewSuggestions:
    if: github.repository == 'asyncapi/website'
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Base Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        path: base
    - name: Checkout PR Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        path: pr
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies and Regenerate for PR
      run: |
        cd pr
        npm install
        npm run generate:tools
    - name: Check and Suggest Changes
      run: |
        git diff -U0 base pr > changes.diff
        while IFS= read -r line; do
          line_content="${line#+}"
          file_name=$(echo "$line" | cut -d' ' -f2)
          start_line=$(echo "$line" | cut -d' ' -f3 | cut -d',' -f1)
          gh pr review ${{ github.event.pull_request.number }} --comment -b "I suggest this change on \`$file_name\`:
          \`\`\`suggestion
          $line_content
          \`\`\`"
        done < changes.diff
